### ISSUE TITLE
The Localgov_alert_banners workflow should be removed when this module is uninstalled

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_alert_banner#213]
Otherwise uninstall / reinstall fails.

Add the module as an enforced dependency in the `workflows.workflow.localgov_alert_banners.yml` file under dependencies.

````yaml
  enforced:
    module:
      - localgov_alert_banner
 ````
