### ISSUE TITLE
Duplicate revisions local tasks on alert banner entitiy

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_alert_banner#302]
Spotted whilst working on another entitiy

<img width="1107" alt="Screenshot 2024-01-16 at 3 34 20 pm" src="https://github.com/localgovdrupal/localgov_alert_banner/assets/1467480/9b9ba97e-990e-41a9-b6c9-f75a2066e7df">

Removing 
```yaml
entity.localgov_alert_banner.version_history:
  route_name: entity.localgov_alert_banner.version_history
  base_route: entity.localgov_alert_banner.canonical
  title: 'Revisions'
```
from `localgov_alert_banner.links.task.yml` resolves the issue, but it's curious if this is a recent Drupal change?
It might be that entitiy was generated during the Drupal 8 days so may need regenererating?
